### ISSUE TITLE
Lasagne not available for x64 Linux on conda

### ISSUE THREAD

**Issue by islamelnabarawy** [Islandman93/reinforcepy#1]
The README file has instructions for installing Lasagne as part of the conda install command for the Linux environment. However, that command gives the following error:

```
$ conda create -n reinforcepy python=3.4 numpy theano lasagne
Fetching package metadata .......
Solving package specifications: .
Error: Package missing in current linux-64 channels: 
  - lasagne

You can search for packages on anaconda.org with

    anaconda search -t conda lasagne
```

Manual install of Lasagne using pip is needed, according to instructions available [here](http://lasagne.readthedocs.io/en/latest/user/installation.html).

**Comment by Islandman93** [comment]
Since we no longer user lasagne I am going to close this issue.
