### ISSUE TITLE
Install instructions not working due to README.rst missing

### ISSUE THREAD

**Issue by alvarosg** [Islandman93/reinforcepy#11]
The installation instructions as provided:
```
    git clone https://github.com/Islandman93/reinforcepy
    cd reinforcepy/
    python setup.py install
```
fail because of the non-existent README.rst file referenced in the setup.py file.

I assume pandoc or similar is normally used to create the .rst file from the .md file during packaging, but this may be confusing for people installing it. Or it may just be residual from before this [PR](https://github.com/Islandman93/reinforcepy/pull/8).

I bypassed it during installation without having to use pandoc by simple `cp README.md README.rst`. We may recommend this to users in the installation instructions,... or we may want to update the setup.py to use the new md file, although I guess it may then have problems with PyPI not handling rst files well, which is probably why it was done in the first place.

I could do a PR myself for this myself if requested ;)

**Comment by Islandman93** [comment]
Good catch, thanks for the detailed issue report!
